version: '3'
services:
  grasscutter:
    image: ayakalab/grasscutter:latest
    restart: always
    volumes:
      - ./mount/grasscutter:/app
    # ports:
    #   - "443:443"

  mongodb:
    image: mongo:4.4.23
    restart: always
    volumes:
      - ./mount/mongodb:/data/db
    # environment:
    #   MYSQL_ROOT_PASSWORD: example_mysql_password
    #   MYSQL_SSL_MODE: disabled
