# docker-compose up
version: '3'
services:
  grasscutter:
    image: ayakalab/grasscutter:latest
    restart: always
    volumes:
      - ./config/grasscutter/config.json:/app/config.json
      # - ./config/grasscutter/keystore.p12:/app/keystore.p12
    ports:
      - "443:443"
  
  mongodb:
    image: mongo:4.4.23
    restart: always
    volumes:
      - ./mount/mongodb:/data/db
